version: "3.3"

services:
  fe-dev:
    build: .
    container_name: fe-dev
    volumes:
      - type: bind
        source: "$PWD/../"
        target: /home/archie/app
    stdin_open: true
    tty: true
    command: zsh
